name: Release Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
          fail-fast: false
          matrix:
            include:
              - os: ubuntu-latest
                target: x86_64-unknown-linux-gnu
                artifact_name: orbit-linux
                binary_path: target/x86_64-unknown-linux-gnu/release/orbit
              - os: windows-latest
                target: x86_64-pc-windows-msvc
                artifact_name: orbit-windows
                binary_path: target/x86_64-pc-windows-msvc/release/orbit.exe

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        # Тепер ми використовуємо точний шлях для кожної ОС окремо
        path: ${{ matrix.binary_path }}
        if-no-files-found: error
